#!/bin/bash

# GitHub and Render Deployment Script
echo "🚀 Activus Invoice System - Render Deployment"
echo "=============================================="

echo ""
echo "📋 Step 1: Create GitHub Repository"
echo "1. Go to https://github.com/new"
echo "2. Repository name: activus-invoice-system"
echo "3. Make it PUBLIC (required for free Render)"
echo "4. Don't initialize with README"
echo "5. Click 'Create repository'"
echo ""

read -p "Press Enter after creating the GitHub repository..."

echo ""
echo "📤 Step 2: Push to GitHub"
echo "Run these commands (replace YOUR_USERNAME with your GitHub username):"
echo ""
echo "git remote add origin https://github.com/YOUR_USERNAME/activus-invoice-system.git"
echo "git push -u origin main"
echo ""

read -p "Press Enter after pushing to GitHub..."

echo ""
echo "🌐 Step 3: Deploy on Render"
echo "1. Go to https://render.com"
echo "2. Sign up with GitHub"
echo "3. Click 'New +' → 'Web Service'"
echo "4. Connect your GitHub repository"
echo "5. Configure the service:"
echo "   - Name: activus-backend"
echo "   - Environment: Docker"
echo "   - Region: Choose closest to you"
echo "   - Branch: main"
echo "   - Root Directory: (leave empty)"
echo "   - Dockerfile Path: Dockerfile"
echo "   - Plan: Free"
echo ""
echo "6. Add Environment Variables:"
echo "   - MONGO_URL: (Render will provide this)"
echo "   - DB_NAME: activus_invoice_db"
echo "   - SECRET_KEY: (generate a random string)"
echo ""
echo "7. Click 'Create Web Service'"
echo ""

echo "🎉 Your app will be available at: https://activus-backend.onrender.com"
echo ""
echo "📚 Additional Resources:"
echo "- Render Docs: https://render.com/docs"
echo "- MongoDB on Render: https://render.com/docs/databases"
echo ""
